### PR TITLE
fix StringCompositor to support underscore and numbers

### LINKED ISSUE #41: binding names with underscores or other characters do not work

### PR DESCRIPTION
**Pull request by XN137**
maybe this fixes #41 ? i am not sure, but it was a bug either way i guess?

i was wondering if there is a special reason why `StringCompositor` and `StringCompositorTest` are in different maven modules?

local test with `mvn clean package`:
```
[INFO] Reactor Summary:
[INFO] 
[INFO] project-defaults ................................... SUCCESS [  0.806 s]
[INFO] metagen-api ........................................ SUCCESS [  7.036 s]
[INFO] metagen-lib-random ................................. SUCCESS [  3.322 s]
[INFO] metagen-lib-basics ................................. SUCCESS [  6.766 s]
[INFO] metagen-lib-composer ............................... SUCCESS [  4.322 s]
[INFO] metagen-lib-curves ................................. SUCCESS [  6.723 s]
[INFO] metagen-userlibs ................................... SUCCESS [ 11.188 s]
[INFO] metagen-lang ....................................... SUCCESS [  6.963 s]
[INFO] metagen-lib-realer ................................. SUCCESS [  2.491 s]
[INFO] metagen ............................................ SUCCESS [  0.172 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50.732 s
[INFO] Finished at: 2017-11-09T10:28:33+01:00
[INFO] Final Memory: 115M/1584M
[INFO] ------------------------------------------------------------------------
```

the DirectoryLinesTest failed for me like this previously:
```
[ERROR] Tests run: 43, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.773 s <<< FAILURE! - in TestSuite
[ERROR] testResourceDirectory(io.virtdata.basicsmappers.from_long.to_string.DirectoryLinesTest)  Time elapsed: 0.019 s  <<< FAILURE!
java.lang.AssertionError: 

Expecting:
 <"data2.txt-line1">
to be equal to:
 <"data1.txt-line1">
but was not.
	at io.virtdata.basicsmappers.from_long.to_string.DirectoryLinesTest.testResourceDirectory(DirectoryLinesTest.java:14)
```
i assume it is because the order of files found depends on the jvm version or platform, thus i added sorting to make it deterministic?

### CODE REVIEW

File: metagen-lib-basics/src/main/java/io/virtdata/basicsmappers/from_long/to_string/DirectoryLines.java [hunk 1]
```diff
@@ -66,7 +66,7 @@ public synchronized String apply(long value) {
             throw new RuntimeException(e);
         }
         logger.debug("File reader: " + fileList.toString() + " in path: " + Paths.get(basepath).getFileName());
-
+        fileList.paths.sort(Path::compareTo);
```
Comment (jshook) [inline metagen-lib-basics/src/main/java/io/virtdata/basicsmappers/from_long/to_string/DirectoryLines.java]: This is not in scope with the comment for the PR. Not a big deal here, but I'll tend to merge PRs that are narrowly themed more quickly.

**Comment by jshook** [comment]
StringCompositorTest references generator libraries indirectly via "Identity()", so it relies on classpath+ServiceLoader awareness of the aggregating module it is in. We could probably simplify the testing to not need it and then move it back.

File: metagen-lib-basics/src/main/java/io/virtdata/basicsmappers/from_long/to_string/DirectoryLines.java (hunk 1 above)
Comment (XN137) [reply metagen-lib-basics/src/main/java/io/virtdata/basicsmappers/from_long/to_string/DirectoryLines.java]: It is already explained in the PR description why i made this change, otherwise i would not have been able to build without having the tests fail on me.
I kept the change on a separate commit.
